# Generated by Django 2.2.5 on 2019-09-28 18:04

import api.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DueDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EnrolledUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=30)),
                ('required', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=30)),
                ('photo', models.TextField()),
                ('date', models.DateTimeField()),
                ('folder', models.CharField(max_length=127)),
                ('valuid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('photouid', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=127)),
                ('owner', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=127)),
                ('dueDates', djongo.models.fields.ArrayModelField(model_container=api.models.DueDate)),
                ('enrolled', djongo.models.fields.ArrayModelField(model_container=api.models.EnrolledUser)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=127)),
                ('email', models.CharField(max_length=127)),
                ('folders', djongo.models.fields.ArrayModelField(model_container=api.models.Folder)),
                ('photos', djongo.models.fields.ArrayModelField(model_container=api.models.Photo)),
                ('trials', djongo.models.fields.ArrayModelField(model_container=api.models.UserTrial)),
            ],
        ),
        migrations.CreateModel(
            name='UserTrial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=30)),
                ('submittedPhotos', djongo.models.fields.ArrayModelField(model_container=api.models.SubmittedPhoto)),
            ],
        ),
    ]
