# Generated by Django 2.2.5 on 2019-09-28 21:10

import api.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190928_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='savePreProcessedPhoto',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='folders',
            field=djongo.models.fields.ArrayModelField(default=1, model_container=api.models.Folder),
            preserve_default=False,
        ),
    ]
