# Generated by Django 2.2.5 on 2019-09-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190928_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='description',
            field=models.CharField(default=1, max_length=999),
            preserve_default=False,
        ),
    ]
